### ISSUE TITLE
Esperanto broken? Unsupported?

### ISSUE THREAD

**Issue by swedebugia** [tkedwards/wiktionarytodict#3]
$ time python3 wiktionarytodict-master/wiktionarytodict3.py enwiktionary-20190901-pages-articles-1miol.xml English:eng Esperanto:epo ~/Hämtningar/wiktionary/output1miol
Traceback (most recent call last):
  File "wiktionarytodict-master/wiktionarytodict3.py", line 256, in <module>
    parser.parse(open(sys.argv[1], 'r'))
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/build/python/src/Python-3.7.3/Modules/pyexpat.c", line 469, in EndElement
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 236, in endElement
    self.processTextElement(self.textchardata)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 47, in processTextElement
    self.parseTranslations(content)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 68, in parseTranslations
    self.parseTranslationline(aline, currentMeaning)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 88, in parseTranslationline
    self.addtoTranslationsMap(wordwithmeaning, translation, currentLanguage)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 124, in addtoTranslationsMap
    newtrans = self.translationstoeng[currentLanguage][translation] + ', {0}'.format(wordwithmeaning)
KeyError: 'Esperanto'

real	0m51,438s
user	0m37,486s
sys	0m13,546s

$ time python3 wiktionarytodict-master/wiktionarytodict3.py enwiktionary-20190901-pages-articles-1miol.xml English:eng Danish:dan Esperanto:epo ~/Hämtningar/wiktionary/output1miol
Traceback (most recent call last):
  File "wiktionarytodict-master/wiktionarytodict3.py", line 256, in <module>
    parser.parse(open(sys.argv[1], 'r'))
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/build/python/src/Python-3.7.3/Modules/pyexpat.c", line 469, in EndElement
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 236, in endElement
    self.processTextElement(self.textchardata)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 47, in processTextElement
    self.parseTranslations(content)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 68, in parseTranslations
    self.parseTranslationline(aline, currentMeaning)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 88, in parseTranslationline
    self.addtoTranslationsMap(wordwithmeaning, translation, currentLanguage)
  File "wiktionarytodict-master/wiktionarytodict3.py", line 124, in addtoTranslationsMap
    newtrans = self.translationstoeng[currentLanguage][translation] + ', {0}'.format(wordwithmeaning)
KeyError: 'Esperanto'

Removing Esperanto and running it gives me:
$ time python3 wiktionarytodict-master/wiktionarytodict3.py enwiktionary-20190901-pages-articles-1miol.xml English:eng Danish:dan ~/Hämtningar/wiktionary/output1miol
Dictionary generation complete
Creating 'jargon' format file (see the -j option in man dictfmt) for English in /home/annika/Hämtningar/wiktionary/output1miol
Creating 'jargon' format file (see the -j option in man dictfmt) for Danish in /home/annika/Hämtningar/wiktionary/output1miol
Creating dict format file (see man dictfmt) for English in /home/annika/Hämtningar/wiktionary/output1miol
           7 headwords
           7 headwords
Creating dict format file (see man dictfmt) for Danish in /home/annika/Hämtningar/wiktionary/output1miol
        3209 headwords
        3195 headwords

real	1m41,462s
user	1m31,799s
sys	0m8,485s

**Comment by tkedwards** [comment]
Thanks for the bug report, I'll take a look at this when I have time. It should support any language for whcih there's entries under Translations in the Wiktionary pages, and it looks like there are plenty of entries for Esperanto, so I'll need to debug why it fails

**Comment by swedebugia** [comment]
Thanks for giving this attention. :) I really appreciate the script.
